### ISSUE TITLE
ERROR Execution failed

### ISSUE THREAD

**Issue by PolarBearGod** [LukeMurphey/splunk-syndication-input#4]
**Current Setup:**  
Splunk Version: 8.1.0  
Splunk Build: f57c09e87251  
Syndication Version: 1.2.4  

Installed successfully and configured with a test RSS feed: http:// www [.] tweettioc [.] com/v1/tweets/daily/full on a 12 hour cycle. I have the following two events using the Troubleshooting query:

`2020-11-23 20:49:40,713 INFO Successfully retrieved feed entries, count=0, url=http://www.tweettioc.com/v1/tweets/daily/full`

```
2020-11-23 20:49:40,714 ERROR Execution failed
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/syndication/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 1095, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "/opt/splunk/etc/apps/syndication/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 976, in do_run
    self.run(stanza, cleaned_params, input_config)
  File "/opt/splunk/etc/apps/syndication/bin/syndication.py", line 379, in run
    if len(results) == 0 and last_entry_date_retrieved > last_entry_date:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

Not really sure of next steps.

**Comment by LukeMurphey** [comment]
It looks like that feed isn't valid. I tried putting it in several online RSS feed parses and they all fail.

I am fixing the issue with the exception so that it handles invalid feeds properly.
