### ISSUE TITLE
Issue on Splunk 8.1.3 server

### ISSUE THREAD

**Issue by rolltidega** [LukeMurphey/splunk-syndication-input#8]
I recently installed the Syndication app on a Splunk 8.1.3 server and I am getting the following error which I did not get on Splunk 7.3.5:

2021-07-27 08:34:20,352 ERROR Execution failed
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/syndication/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 1095, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "/opt/splunk/etc/apps/syndication/bin/modular_input.zip/modular_input/modular_input_base_class.py", line 976, in do_run
    self.run(stanza, cleaned_params, input_config)
  File "/opt/splunk/etc/apps/syndication/bin/syndication.py", line 383, in run
    if last_entry_date_retrieved is not None and last_entry_date_retrieved > last_entry_date:
TypeError: '>' not supported between instances of 'time.struct_time' and 'NoneType'

It seems like maybe something with Python3 since it worked on 7.3.5 which used Python2.  Any quick fixes here?

**Comment by snackysm0res** [comment]
I'm running into the same issue as well. I found a potential fix here: https://community.splunk.com/t5/All-Apps-and-Add-ons/Syndication-Input-RSS-ATOM-RDF-Add-On/m-p/567160#M75143

But oddly, when I attempt to edit syndication.py—even an inconsequential test edit like adding `test_variable = "test"`—the add-on disappears from Splunk Web and won't run its scripts anymore.

@LukeMurphey do you know why the add-on would stop working just from making _any_ changes to syndication.py?

**Comment by jcoustello** [comment]
I ran in the same issue too. I followed the community.splunk.com link above and applied the modifications to the syndication.py script. 

For the record :msg from Chikuwa

bin/syndication.py: 

170c170
<         latest_date = None
---
>         latest_date = time.gmtime(0)
343c343
<                 last_entry_date = None
---
>                 last_entry_date = time.gmtime(0)
347c347
<             last_entry_date_retrieved = None
---
>             last_entry_date_retrieved = time.gmtime(0)
383c383
<                 if last_entry_date_retrieved is not None and last_entry_date_retrieved > last_entry_date:
---
>                 if last_entry_date_retrieved !=0 and last_entry_date_retrieved > last_entry_date:

I initially made a typo and the app disappeared also after the restart.
Looking at the Splunk logs, I was able to find an entry that pointed to the syntax error, I fixed it and restarted and the app was back and the previous error msg were gone. The app seems to be working now.
